<?php

/**
 * @file
 * Contains andrewpage.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function andrewpage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the andrewpage module.
    case 'help.page.andrewpage':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A page using twig template, a route and controller') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 *
 * Register a module or theme's implementations.
 * The implementations declared by this hook specify how a particular render array
 * is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php
/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing table 'drush cc theme-registry'
 * and 'drush cc router'
 */
function andrewpage_theme($existing, $type, $theme, $path) {
  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'andrewpage_theme_hook' => [
      'render element' => 'children',
      // If no template name is defined here, it defaults to the name of the theme hook, ie.
      // module-name-theme-hook.html.twig
      'template' => 'andrewpage',
      // Optionally define path to Twig template files. Defaults to the module's ./templates/
      // directory.
      'path' => $path . '/templates',
      // Optionally define variables that will be passed to the twig template and set default
      // values for them.
      'variables' => [
        'variable1' => 'Yet another default text',
        'variable2' => 0,
        'variable3' => [0,0,0],
      ],
    ],
    ];

}
